---

#- name: Ensure tomcat_java_home is defined
#  fail: msg="You must define the tomcat_java_home variable"
#  when: tomcat_java_home is not defined

- name: Create tomcat group
  group:
    name: tomcat
    system: true

- name: Create tomcat user
  user:
    name: tomcat
    group: tomcat
    shell: /bin/false
    home: "{{tomcat_home_path}}"
    system: true
    createhome: false
    #move_home: true

- name: Download Tomcat archieve
  get_url: url={{ tomcat_url }} dest=/opt/{{ tomcat_package }}

#- name: Create tomcat home directory
#  file:
#    path: "{{tomcat_home_path}}"
#    state: directory
#    group: tomcat
#    mode: 0755

- name: Extract tomcat archive
  command: chdir=/opt /bin/tar xvf /opt/{{ tomcat_package }} -C /opt creates=/opt/{{ tomcat_build_name }}

- name: Rename directory
  command: cp -r /opt/{{ tomcat_build_name }} {{tomcat_home_path}}

- name: Change ownership
  file:
    path: "{{tomcat_home_path}}"
    mode: 0755
    group: tomcat
    state: directory
    recurse: yes

  #become: yes
  #- name: Create and change tomcat directory permission
  #  copy:
  #    src: "tomcat_ur"
  #    dest: "{{tomcat_home_path}}"
  #    remote_src: yes
  #    group: tomcat
  #    mode: 0750
  #    directory_mode: yes
  #recurse: yes



#- name: Download and extract Tomcat to tomcat home directory
#  unarchive:
    #src: "{{ tomcat_archive_url}}/{{tomcat_archive_name}}{{tomcat_archive_name_ext }}"
    #src: "/opt/{{ tomcat_package }}"
#    src: "{{ tomcat_url }}"
#    dest: "{{ tomcat_home_path }}"
#    remote_src: yes
    #group: tomcat
    #mode: 0750
    #creates: "{{tomcat_archive_install_path}}"

- name: Make the tomcat user the owner of the webapps, work, temp, and logs directories
  file:
    #path: "{{tomcat_archive_install_path}}/{{item}}"
    path: "{{tomcat_home_path}}/{{item}}"
    owner: tomcat
    group: tomcat
    recurse: true
  with_items:
    - webapps
    - work
    - temp
    - logs

- name: Grant Tomcat group read access to the conf directory
  file:
    state: directory
    path: "{{tomcat_home_path}}/conf"
    mode: "g+r"
    recurse: true

- name: Grant Tomcat group execute access to the conf directory itself
  file:
    path: "{{tomcat_home_path}}/conf"
    state: directory
    mode: "g+x"

#- name: Grant Tomcat group access to the bin directory itself
#  file:
#    path: "{{tomcat_home_path}}/bin"
#    group: tomcat
#    state: directory
#    mode: "g+rwx"

#- name: Create tomcat-users.xml
#  template:
#    src: templates/tomcat-users.xml
#    dest: "{{tomcat_home_path}}/conf/tomcat-users.xml"
#  notify: restart tomcat

#- name: Symlink Tomcat to current version
#    src: "/opt/{{ tomcat_build_name }}"
#    dest: "{{ tomcat_install_link }}"
#    state: link
#  notify: restart tomcat

- name: Create systemd service script for Tomcat
  template:
    src: "templates/tomcat.service"
    dest: "/etc/systemd/system/tomcat.service"
  notify:
    - reload systemd
    - restart tomcat
  tags: [systemd]
#- name: Start and enable Tomcat service
#  systemd:
#    name: tomcat
#    state: started
#    enabled: true
#    daemon_reload: true
