---

- name: SolrCloud | Install
  import: install.yml
  tags:
    - install

- name: SolrCloud | Configure
  include: config.yml
  tags:
    - configure

- name: SolrCloud | Service
  include: service.yml
  tags:
    - service
